-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "Attack Coin"
local A_2 = game:GetService("Workspace").Coins.Spawn.Coin
local Event = game:GetService("ReplicatedStorage").Remotes.Function
Event:InvokeServer(A_1, A_2)
