-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "+FS1"
}
local Event = game:GetService("ReplicatedStorage").RemoteEvent
Event:FireServer(A_1)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "+BT1"
}
local Event = game:GetService("ReplicatedStorage").RemoteEvent
Event:FireServer(A_1)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "+MS1"
}
local Event = game:GetService("ReplicatedStorage").RemoteEvent
Event:FireServer(A_1)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "+JF1"
}
local Event = game:GetService("ReplicatedStorage").RemoteEvent
Event:FireServer(A_1)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "+PP1"
}
local Event = game:GetService("ReplicatedStorage").RemoteEvent
Event:FireServer(A_1)
