-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = true
local A_2 = "Axe"
local Event = game:GetService("ReplicatedStorage").Gathering.API.ToggleTool
Event:FireServer(A_1, A_2)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 1
local Event = game:GetService("Workspace").Gathering.Wood["Spawn-V2"]["WoodSpawn-Island-Arch-10"].Small.Gathering.GatherEvent
Event:FireServer(A_1)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = false
local Event = game:GetService("ReplicatedStorage").Gathering.API.ToggleTool
Event:FireServer(A_1)
