-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero

local A_1 = "equip"
local A_2 = game:GetService("Workspace").WAOHoukaShu.Weight.Handle.Mesh
local Event = game:GetService("Players").WAOHoukaShu.strengthEvent
Event:FireServer(A_1, A_2)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero

local A_1 = "rep"
local A_2 = game:GetService("Workspace").WAOHoukaShu.Weight.Handle.Mesh
local Event = game:GetService("Players").WAOHoukaShu.strengthEvent
Event:FireServer(A_1, A_2)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero

local A_1 = "unequip"
local A_2 = game:GetService("Players").WAOHoukaShu.Backpack.Weight.Handle.Mesh
local Event = game:GetService("Players").WAOHoukaShu.strengthEvent
Event:FireServer(A_1, A_2)