-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 1 --or 2
local A_2 = game:GetService("Workspace").Levels.Forest.Enemies.Dummy
local Event = game:GetService("ReplicatedStorage").Remote.CastSpell
Event:FireServer(A_1, A_2)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = game:GetService("Workspace").Levels.Forest.BC.Trigger
local Event = game:GetService("ReplicatedStorage").Remote.OpenChest
Event:FireServer(A_1)
