-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "MineBlock"
local A_2 = 
{
	[1] = 
{
	[1] = game:GetService("Workspace").Blocks.Dirt
}
}
local Event = game:GetService("Workspace")["r̀·̀ŒÍ€Í”̀—̀˜̀—̀±è¶̀‡̀•̀¿̀¿Í„̀̀ŒÍ›Í˜ÍÍ̀…̀„Í“m̀·Í‚Í̀ˆ̀„̀̀¿ÍƒÍ„̀̀ŒÍ̀¯̀¬̀¬̀¤̀¥̀œ̀²òµ̀†̀Íƒ̀†Í„"]
Event:FireServer(A_1, A_2)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "MoveTo"
local A_2 = 
{
	[1] = 
{
	[1] = "SurfaceSpawn"
}
}
local Event = game:GetService("Workspace")["r̀·̀ŒÍ€Í”̀—̀˜̀—̀±è¶̀‡̀•̀¿̀¿Í„̀̀ŒÍ›Í˜ÍÍ̀…̀„Í“m̀·Í‚Í̀ˆ̀„̀̀¿ÍƒÍ„̀̀ŒÍ̀¯̀¬̀¬̀¤̀¥̀œ̀²òµ̀†̀Íƒ̀†Í„"]
Event:FireServer(A_1, A_2)
