-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local Event = game:GetService("ReplicatedStorage").Events.AreaSell
Event:FireServer()

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = game:GetService("Workspace").SandBlocks["11, -560.5, -220"]
local Event = game:GetService("Workspace").WAOHoukaShu.Bucket.RemoteClick
Event:FireServer(A_1)

-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local Event = game:GetService("ReplicatedStorage").Events.GetStats
Event:InvokeServer()
-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local Event = game:GetService("ReplicatedStorage").Events.UpdateLeaderstats
Event:FireServer()
